### ISSUE TITLE
render command inserts unsupported flag

### ISSUE THREAD

**Issue by amar-ox** [hiberbee/github-action-skaffold#14]
In CI pipeline, when using skaffold render command with parameter `--output=render.yaml`, a `--skip-tests` flag is inserted which causes: known flag: --skip-tests. This flag is not used in the render command according to the documentation.  
Build command works fine.
Version 1.17.0

**Comment by vladyslavvolkov** [comment]
@amar-ox Thanks for report, will fix soon

**Comment by vladyslavvolkov** [comment]
@amar-ox please, check latest release [1.18](https://github.com/hiberbee/github-action-skaffold/releases/tag/1.18.0) for fix you've reported
